### ISSUE TITLE
Cloning as submodule

### ISSUE THREAD

**Issue by rbovard** [3nids/qgissettingmanager#2]
Hi Denis,

When cloning a project (`quickfinder`) with `qgissettingmanager` as submodule, I have a right issue:

````
Submodule 'qgissettingmanager' (git@github.com:3nids/qgissettingmanager.git) registered for path 'qgissettingmanager'
Cloning into 'qgissettingmanager'...
ssh: connect to host github.com port 22: Bad file number
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:3nids/qgissettingmanager.git' into submodule path 'qgissettingmanager' failed
````

How can I get through this?

Thanks :)

**Comment by 3nids** [comment]
it seems to be an issue of git.

1. Clone the quickfinder repo without using `--recursive` option
2. in qgissettingmanager folder, do `git submodule update --init` => produces an error (ok)
3. edit quickfinder/.git/config and replace the submodule git url by the https one `https://github.com/3nids/qgissettingmanager.git`
4. do again `git submodule update --init` in qgissettingmanager folder

this should work

**Comment by rbovard** [comment]
Thanks, this worked :+1:

**Comment by rbovard** [comment]
Maybe you should update the doc about that? I can do it, but I'm not sure if it's the right way (I don't know a lot about submodules)...

https://github.com/3nids/qgissettingmanager/blob/master/README.md#using-git-submodules

**Comment by 3nids** [comment]
This documentation is about how adding the library to one of your existing plugin and is valid in this case.
The non documented case is related to the quickfinder plugin on how to git clone properly...
I'm no git expert either ;) so, wait and see...or go for it...
