### ISSUE TITLE
disconnect signal when setting value (to avoid loop)

### ISSUE THREAD

**Issue by 3nids** [3nids/qgissettingmanager#6]

**Comment by m-kuhn** [comment]
or only set value if there has been a change?

**Comment by 3nids** [comment]
Good advice, glad to see you're following here too ;)  BTW, I'm thinking about moving this to qgis core. The idea would be both to offer this library to plugin devs but also to have a central place for qgis core settings to have an overview of the settings, a more coherent naming, avoid misspelling or different default values in value calls.

**Comment by m-kuhn** [comment]
What would be the difference compared to the settings editor we already have in options?

Type safety and "registered" setting keys?

**Comment by 3nids** [comment]
One would not replace the other, it's complementary.

The idea is that adding settings to qgis would be only done in the main QgsSettings class (and not using QSettings). Advantages:

* one place for all settings: overview
* avoid repeating default value at every call (and risk of having different values)
* avoid risk of mispelling when calling value (and thus alway get default value)

The second advantage is the handling of the widgets: setting/reading value is done automatically by the class.

Does it make sense to you?

**Comment by m-kuhn** [comment]
I guess settings in QgsSettings will need to be registered (with default value etc.).
Would that be done centralized (e.g. a huge table in qgssettings.cpp) or on first usage?

**Comment by 3nids** [comment]
Yes that would mean a huge table. Do you think it's a bad idea?

**Comment by m-kuhn** [comment]
I wonder for the modularity. For QGIS that could reside in app, but then it will probably not be possible to use it outside (standalone apps, server)? And plugins would also have to find another way.

**Comment by 3nids** [comment]
I think it should be in core, don't you?

The idea would be to offer the base API class so they can register they own...

**Comment by m-kuhn** [comment]
I'm not sure app and gui settings should be listed in core, but as long as there's an API around to offer more settings, it should be possible to take care of that (but then we will not have the big table).

**Comment by 3nids** [comment]
rethinking, it seems more logical that all settings are in app, since they are obviously app-dependant.

But that doesn't prevent using the mechanism in plugins:

You have the QgsSettingManager in core, the QgsSettingDialog in gui and an instance of QgsSettingManager in app, let's call it QgsSettingRegistry.

Plugin would use both QgsSettingManager and QgsSettingDialog.
We could offer a pointer the QgsSettingRegistry in the API so plugins could even easily read QgisSettings.

**Comment by m-kuhn** [comment]
If you need a setting in core, let's say QgsTolerance needs a setting "/qgis/digitizing/search_radius_vertex_edit". Would you register it in app?

If a standalone app uses QgsTolerance, will it also need to register the same setting?

**Comment by 3nids** [comment]
correct, that probably mean splitting registering of setting at 3 levels or more (server?).

that would still be feasible though.
QgsSettingRegistryApp extends QgsSettingRegistryGui extends QgsSettingRegistryCore.

**Comment by m-kuhn** [comment]
Are settings defined at compiletime or runtime?

I mean like this:

compile time

    // analog to Q_PROPERTY
    QGS_SETTING( int tolerance MEMBER mTolerance )

runtime

    iface.settings().registerSetting( "tolerance", QVariant.Int, 3 );

**Comment by m-kuhn** [comment]
Runtime will be required if plugins should use the same infrastructure.

Compile time would be nice because the compiler will complain on types and the IDE could (theoretically) offer autocompletion.

What's your idea, how should the system react if somebody tries to access an unregistered setting?

**Comment by 3nids** [comment]
I see.
It would have been nice to see the compiler complaining, but then I suppose it means compile time definition.
Anyway, I think it's maybe not the best idea to use the same infrastructure for the plugins as they also deal with project properties. Do you think the core class should also offer this?

**Comment by m-kuhn** [comment]
For what would you use it?

 * App props
 * Plugin props
 * Project props
 * Layer props

**Comment by 3nids** [comment]
at least the first 3, maybe for layers too.

**Comment by m-kuhn** [comment]
So there's a setting manager in the project (to which app and plugins can write)
And a setting manager in core (to which app and plugins can write)
Or is there one setting manager per module (core, gui, one per plugin, project, ...)

**Comment by 3nids** [comment]
One per module.
For instance, each plugin must subclass the setting manager as now in current library.

**Comment by 3nids** [comment]
@m-kuhn I couldn't find a way to use your idea. Some updates are made progressively (like in listboxes), so it's not possible to test the value form the widget while updating.

if you have a better idea, let me know :)
